name: CI

on:
  push:
    branches: [ main, develop, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff black mypy pytest
      - name: Lint (ruff)
        run: ruff check .
      - name: Format (black --check)
        run: black --check .
      - name: Type check (mypy)
        run: mypy src || true  # temporary non-fatal until types hardened
      - name: Tests
        run: pytest -q
      - name: Provenance preview
        run: |
          python -c "from pathlib import Path; print('Repo files:', len(list(Path('.').rglob('*'))))"
